name: 全平台自动构建

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macos-12]

    steps:
      - name: 初始化Repo
        uses: actions/checkout@main
        with:
          lfs: true

      - name: 初始化Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel
          pip install --upgrade -r requirements.txt
          pip install pyinstaller==6.10.0

      - name: 重构建 PyInstaller Bootloader (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          git clone https://github.com/pyinstaller/pyinstaller.git --depth 1 --branch "v6.10.0"
          cd pyinstaller/bootloader
          python ./waf all
          rm -r "$(python -c "import os, sys; print(os.path.dirname(sys.executable))")/Lib/site-packages/PyInstaller/bootloader"
          cp -r "../PyInstaller/bootloader" "$(python -c "import os, sys; print(os.path.dirname(sys.executable))")/Lib/site-packages/PyInstaller"

      - name: 安装 Tkinter (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install python-tk@3.12 && echo -n 'export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.zshrc && source ~/.zshrc && echo -n 'export PATH="/usr/local/opt/python/libexec/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc

      - name: 构建 GModCEFCodecFix 主程序
        run: ${{ runner.os == 'Windows' && 'iex ' || ''}}$(cat pyinstaller_${{ runner.os == 'Windows' && 'windows' || runner.os == 'Linux' && 'linux' || 'macos' }}.txt)

      - name: 获取最后一次 Release
        id: latest-release
        uses: actions/github-script@main
        with:
          script: |
            return github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

      - name: 推送到 Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ fromJSON(steps.latest-release.outputs.result).data.upload_url }}
          asset_path: ./dist/GModCEFCodecFix${{ runner.os == 'Windows' && '.exe' || '' }}
          asset_name: GModCEFCodecFix-${{ runner.os }}${{ runner.os == 'Windows' && '.exe' || '' }}
          asset_content_type: application/octet-stream
